version: '3.7'

services:

  mysql:
    image: mariadb:10.5.8-focal
    container_name: mysql
    restart: "no"
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp-database
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: "no"
    ports:
      - 8090:80

  composer:
    image: composer:latest
#    build:
#      context: .
#      dockerfile: Dockerfile-composer
    volumes:
      - ./wordpress:/app
    command: composer install

  wordpress:
    image: wordpress:5.7.1-fpm-alpine
    depends_on:
      - composer
      - mysql
    container_name: wordpress
    ports:
      - 9000:9000
    working_dir: /var/www/html
    restart: on-failure:5
    volumes:
      - ./wordpress:/var/www/html
#      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:     
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wp-database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: shop_
      WORDPRESS_DEBUG: 1

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 8081:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
    environment:
      - NGINX_HOST=khaning.test
      - NGINX_PORT=80
    links:
      - wordpress
    restart: "no"
    
volumes:
  db_data:
