apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass.name | default "-" }}
  resources:
    requests:
      storage: 5Gi