{{- if .Values.nginx.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rf-wordpress.fullname" . }}-certs
  labels:
    {{- include "rf-wordpress.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "certs/*").AsSecrets | indent 2 }}
{{- end }}