{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-fastcgi
data:
  SCRIPT_FILENAME: "/var/www/html/index.php"
  FASTCGI_PASS: {{ include "rf-wordpress.fullname" . }}:{{ .Values.wordpress.service.port }}
{{- end }}