{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rf-wordpress.fullname" . }}-nginx
  labels:
    {{- include "rf-wordpress.labels" . | nindent 4 }}-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - protocol: TCP
      name: nginx
      port: {{ .Values.nginx.service.port }}
    {{- if .Values.nginx.ssl.enabled }}
      targetPort: 443
    {{- else }}
      targetPort: 80
    {{- end }}     
  selector:
    {{- include "rf-wordpress.selectorLabels" . | nindent 4 }}
{{- end }}    