apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rf-wordpress.fullname" . }}-db-secrets
type: Opaque
data:
  WORDPRESS_DB_NAME: {{ .Values.wordpress.database.WORDPRESS_DB_NAME | b64enc }}
  WORDPRESS_DB_USER: {{ .Values.wordpress.database.WORDPRESS_DB_USER | b64enc }}
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.database.WORDPRESS_DB_PASSWORD | b64enc }}